import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Webpack
precacheAndRoute(self.__WB_MANIFEST);

// Add your custom service worker logic here
self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});